# Generated by Django 4.1.7 on 2023-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='description',
        ),
        migrations.AddField(
            model_name='billing',
            name='tablet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
