# Generated by Django 4.1.7 on 2023-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_billing_description_billing_tablet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='price',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='quantity',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='tablet',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
