# Generated by Django 4.1.7 on 2023-04-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_billing_price_alter_billing_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='drug_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
